namespace ComplianceApi.Models
{
    public class User
    {
        public int Id { get; set; }
        public string FullName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public string PasswordHash { get; set; } = string.Empty;

        // Employee, Manager, HREmployee, HRManager
        public string Role { get; set; } = "Employee";

        // Human-readable per-role code shown in the UI instead of the raw Id
        // (e.g. "E004", "M002", "HR001", "HRM001"). The database still uses
        // Id for every relationship — this is purely a display/reference field,
        // generated by Services/DisplayIdGenerator.cs whenever a user is
        // created or has their role changed.
        public string? DisplayId { get; set; }

        public string AccountStatus { get; set; } = "Active"; // Active, Inactive

        // Was DateTime.Now — mixed with LastLoginAt's DateTime.UtcNow this caused
        // inconsistent timestamps depending on the server's local timezone.
        // Everything on this entity is UTC now; convert to local time only in the UI.
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? LastLoginAt { get; set; }

        // Reporting hierarchy (already existed — unchanged). This is
        // deliberately generic: ManagerId can point to a Manager, a
        // Sub-Manager (still Role == "Manager", just nested), or an
        // HRManager. Multi-level hierarchy falls out of this for free —
        // an employee's manager can itself have a ManagerId pointing further
        // up, with no depth limit.
        public int? ManagerId { get; set; }
        public User? Manager { get; set; }
        public ICollection<User>? DirectReports { get; set; }

        // Department relationship
        public int? DepartmentId { get; set; }
        public Department? Department { get; set; }
    }
}